### ISSUE TITLE
[Non-Urgent/Support req.] Error: Provided message is not an object

### ISSUE THREAD

**Issue by Ju1-js** [torikushiii/hoyolab-auto#46]
This tool has been working great for me. However, I'm having issues setting up the discord webhook notifier. I've attached my config and the error message below. 

Are there any glaring errors in my config?

Note: ... is just redacted parts of the file.
```
2024-08-04 00:00:01 <INFO:Client> {
  message: 'Unhandled promise rejection',
  args: {
    reason: Error: Provided message is not an object
    - args: {"message":{"type":"string","constructor":"String"}}
        at Webhook.send (/home/.../Documents/GitHub/hoyolab-auto/platforms/webhook.js:16:10)
        at Object.checkIn [as code] (/home/.../Documents/GitHub/hoyolab-auto/crons/check-in/index.js:81:20)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      [cause]: undefined
    }
  }
}
```
```
{
    loglevel: 'info',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
    platforms: [
        {
            id: 1,
            active: true,
            type: 'discord', // This platform is optional, only use this if you have want to access commands via Discord bot
            botId: '12...8', // Your Discord bot ID
            token: 'MT...E',
        },
        {
            id: 2,
            active: true, // Set to true if you want to send notification to Discord webhook
            type: 'webhook',
            url: 'https://discord.com/api/webhooks/12...3/gj...l', // You can follow this guide to create a webhook: https://github.com/torikushiii/hoyolab-auto/blob/main/setup/DISCORD_WEBHOOK.md
        },
    ],
    crons: {
        whitelist: [], // You can whitelist some crons if you only want to run specific crons
        blacklist: [], // You can blacklist some crons if you don't want to run them
        // You can use this site to generate cron expression: https://crontab.guru/
        checkIn: '0 0 0 * * *',
        codeRedeem: '*/15 * * * *',
        dailiesReminder: '0 0 21 * * *',
        howlScratchCard: '0 0 21 * * *',
        expedition: '0 */30 * * * *',
        missedCheckIn: '0 0 23 * * *',
        realmCurrency: '0 */1 * * *',
        shopStatus: '0 */1 * * *',
        stamina: '0 */30 * * * *',
        weekliesReminder: '0 0 21 * * 0',
    },
    accounts: [
        {
            id: 1,
            active: true, // Set to true if you want to enable Genshin Impact
            type: 'genshin',
            data: [
                {
                    cookie: 'mi18nLang=... HYV_LOGIN_PLATFORM_LOAD_TIMEOUT={}; HYV_LOGIN_PLATFORM_TRACKING_MAP={}',
                    // Enable this if you want to automatically redeem codes
                    // Please note that if you have one account with characters in multiple servers
                    // the code will be redeemed but you won't get the reward
                    // so please be careful when enabling this, and only enable it on the account that you want to redeem the code
                    redeemCode: true,
                    dailiesCheck: false, // Enable this if you want to get reminded to do your daily commissions
                    weekliesCheck: false, // Enable this if you want to get reminded to do your weeklies
                    realm: {
                        check: false,
                        persistent: false,
                    },
                    stamina: {
                        check: false, // Enable this if you want to get notified when your stamina is above the threshold
                        threshold: 150, // Your stamina threshold, only fires notification when your stamina is above this value
                        persistent: false, // Set to true if you want to get notified every time your stamina is above the threshold
                    },
                    expedition: {
                        check: false, // Enable this if you want to get notified when your expedition is done
                        persistent: false, // Set to true if you want to get notified every time your expedition is done
                    },
                },
            ],
        },
        {
            id: 2,
            active: true,
            type: 'zenless',
            data: [
                {
                    cookie: 'mi18nLang=... HYV_LOGIN_PLATFORM_LOAD_TIMEOUT={}; HYV_LOGIN_PLATFORM_TRACKING_MAP={}',
                    redeemCode: true,
                    shopStatus: true, // This will check if your shop has finished selling videos
                    dailiesCheck: true,
                    stamina: {
                        check: true,
                        threshold: 200,
                        persistent: false,
                    },
                },
            ],
        },
    ],
}
```
P.S. It's likely that this is simply user error, but I wasn't able to figure it out myself. Hopefully, this isn't too much of a burden...

**Comment by torikushiii** [comment]
It seems that the message being passed to the webhook to send notifications is not in the correct format.

Are you comfortable by going to here https://github.com/torikushiii/hoyolab-auto/blob/652f00e5964665fb1e3515e0a70c0383082691f3/platforms/webhook.js#L15-L25

and add `console.log(message)` at here

```javascript
if (typeof message !== "object") {
	console.log(message) // Add this
	throw new app.Error({
		message: "Provided message is not an object",
		args: {
			message: {
				type: typeof message,
				constructor: message?.constructor?.name ?? "N/A"
			}
		}
	});
}
```

it should print a log to see what type of message is being passed

**Comment by Ju1-js** [comment]
I've applied the changes, here's the new log:
```
2024-08-04 13:36:32 <[32mINFO[39m:System> Log level set to info
2024-08-04 13:36:32 <[32mINFO[39m:Client> Loading configuration data
2024-08-04 13:36:32 <[32mINFO[39m:Client> Loaded 5 configuration entries
2024-08-04 13:36:32 <[32mINFO[39m:Cron> Initialized 11 cron jobs
2024-08-04 13:36:32 <[32mINFO[39m:Discord> Registering application commands.
2024-08-04 13:36:33 <[32mINFO[39m:Discord> Successfully registered 5 application commands.
2024-08-04 13:36:34 <[32mINFO[39m:GenshinImpact> Logged into (6...) J... (NA)
2024-08-04 13:36:34 <[32mINFO[39m:ZenlessZoneZero> Logged into (1...) J... (NA)
2024-08-04 13:36:34 <[32mINFO[39m:Client> Initialize completed (2256.753577ms)
📢 Stamina Reminder, Your stamina is within the set threshold\!
🎮 **Game**: Zenless Zone Zero
🆔 **UID**: 1... J...
🌍 **Region**: NA
🔋 **Stamina**: 236/240
🕒 **Recovery Time**: 21 min, 51 sec
2024-08-04 14:00:02 <[32mINFO[39m:Client> {
  message: 'Unhandled promise rejection',
  args: {
    reason: Error: Provided message is not an object
    - args: {"message":{"type":"string","constructor":"String"}}
        at Webhook.send (/home/.../Documents/GitHub/hoyolab-auto/platforms/webhook.js:17:31)
        at Object.stamina [as code] (/home/.../Documents/GitHub/hoyolab-auto/crons/stamina/index.js:96:21) {
      [cause]: undefined
    }
  }
}
🛒 Shop Status
UID: 1... J...
Your shop has finished selling videos\!
2024-08-04 14:00:03 <[32mINFO[39m:Client> {
  message: 'Unhandled promise rejection',
  args: {
    reason: Error: Provided message is not an object
    - args: {"message":{"type":"string","constructor":"String"}}
        at Webhook.send (/home/.../Documents/GitHub/hoyolab-auto/platforms/webhook.js:17:31)
        at Object.shopStatus [as code] (/home/.../Documents/GitHub/hoyolab-auto/crons/shop-status/index.js:76:21) {
      [cause]: undefined
    }
  }
}
```

**Comment by torikushiii** [comment]
I somewhat see the problem, for some reason it tried to send `Telegram` format message, at your config file, it should look like this:

![image](https://github.com/user-attachments/assets/d3a8bbf0-95eb-43fa-a9ca-0d829a598628)

1. is for Discord bot to receive commands
2. is for Telegram
3. and this one is for webhook

for some reason 2 and 3 is flipped out when it tried to prepare message, can you re-check your config file again to see if `webhook` is at id 3 and is active, if you're not using telegram try to disable it

**Comment by Ju1-js** [comment]
I've applied the changes, here's the new log:
```
2024-08-04 13:36:32 <[32mINFO[39m:System> Log level set to info
2024-08-04 13:36:32 <[32mINFO[39m:Client> Loading configuration data
2024-08-04 13:36:32 <[32mINFO[39m:Client> Loaded 5 configuration entries
2024-08-04 13:36:32 <[32mINFO[39m:Cron> Initialized 11 cron jobs
2024-08-04 13:36:32 <[32mINFO[39m:Discord> Registering application commands.
2024-08-04 13:36:33 <[32mINFO[39m:Discord> Successfully registered 5 application commands.
2024-08-04 13:36:34 <[32mINFO[39m:GenshinImpact> Logged into (6...) J... (NA)
2024-08-04 13:36:34 <[32mINFO[39m:ZenlessZoneZero> Logged into (1...) J... (NA)
2024-08-04 13:36:34 <[32mINFO[39m:Client> Initialize completed (2256.753577ms)
📢 Stamina Reminder, Your stamina is within the set threshold\!
🎮 **Game**: Zenless Zone Zero
🆔 **UID**: 1... J...
🌍 **Region**: NA
🔋 **Stamina**: 236/240
🕒 **Recovery Time**: 21 min, 51 sec
2024-08-04 14:00:02 <[32mINFO[39m:Client> {
  message: 'Unhandled promise rejection',
  args: {
    reason: Error: Provided message is not an object
    - args: {"message":{"type":"string","constructor":"String"}}
        at Webhook.send (/home/.../Documents/GitHub/hoyolab-auto/platforms/webhook.js:17:31)
        at Object.stamina [as code] (/home/.../Documents/GitHub/hoyolab-auto/crons/stamina/index.js:96:21) {
      [cause]: undefined
    }
  }
}
🛒 Shop Status
UID: 1... J...
Your shop has finished selling videos\!
2024-08-04 14:00:03 <[32mINFO[39m:Client> {
  message: 'Unhandled promise rejection',
  args: {
    reason: Error: Provided message is not an object
    - args: {"message":{"type":"string","constructor":"String"}}
        at Webhook.send (/home/.../Documents/GitHub/hoyolab-auto/platforms/webhook.js:17:31)
        at Object.shopStatus [as code] (/home/.../Documents/GitHub/hoyolab-auto/crons/shop-status/index.js:76:21) {
      [cause]: undefined
    }
  }
}
```

**Comment by Ju1-js** [comment]
Thanks for the help. I would've thought that it would base the message off the type value in the config. Thanks for all the help!
