### ISSUE TITLE
Codes should be checked only for enabled games

### ISSUE THREAD

**Issue by YozenPL** [torikushiii/hoyolab-auto#50]
Hello,

Application is checking the codes for the games which are not enabled. I believe the codes should be checked only for enabled games.
For me it is GI and ZZZ but somehow I got this message on the console:
![obraz](https://github.com/user-attachments/assets/6f8a95a7-5751-4865-b190-e0589618f10a)
![obraz](https://github.com/user-attachments/assets/bd11c52a-34ff-4e1e-8479-ead9cee12d94)
![obraz](https://github.com/user-attachments/assets/43357d48-7e54-4aaa-8cd3-dea6850ef869)

**Comment by torikushiii** [comment]
oh yeah, i forgot to remove the body response... Sorry about that, should be good at the latest commit now 👍

**Comment by YozenPL** [comment]
Latest git pull and issue is still there:

`2024-08-19 09:30:30 <INFO:GotRequest> {
  error: RequestError: Timeout awaiting 'request' for 30000ms
      at ClientRequest.<anonymous> (file:///home/pi/scripts/hoyolab-auto/node_modules/got/dist/source/core/index.js:670:61)
      at Object.onceWrapper (node:events:634:26)
      at ClientRequest.emit (node:events:531:35)
      at emitErrorNT (node:internal/streams/destroy:169:8)
      at emitErrorCloseNT (node:internal/streams/destroy:128:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      at Timeout.timeoutHandler [as _onTimeout] (file:///home/pi/scripts/hoyolab-auto/node_modules/got/dist/source/core/timed-out.js:33:25)
      at listOnTimeout (node:internal/timers:575:11)
      at process.processTimers (node:internal/timers:514:7) {
    input: undefined,
    code: 'ETIMEDOUT',
    timings: {
      start: 1724052600097,
      socket: 1724052600269,
      lookup: undefined,
      connect: undefined,
      secureConnect: undefined,
      upload: 1724052600269,
      response: undefined,
      end: undefined,
      error: 1724052630103,
      abort: undefined,
      phases: [Object]
    },
    name: 'TimeoutError',
    options: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
        origin: 'https://api.ennead.cc',
        protocol: 'https:',
        username: '',
        password: '',
        host: 'api.ennead.cc',
        hostname: 'api.ennead.cc',
        port: '',
        pathname: '/starrail/code',
        search: '',
        searchParams: URLSearchParams {},
        hash: ''
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: false
    },
    event: 'request',
    [cause]: TimeoutError: Timeout awaiting 'request' for 30000ms
        at Timeout.timeoutHandler [as _onTimeout] (file:///home/pi/scripts/hoyolab-auto/node_modules/got/dist/source/core/timed-out.js:33:25)
        at listOnTimeout (node:internal/timers:575:11)
        at process.processTimers (node:internal/timers:514:7) {
      event: 'request',
      code: 'ETIMEDOUT'
    }
  },
  context: {
    code: 'ETIMEDOUT',
    responseType: 'json',
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: 30000,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    url: 'https://api.ennead.cc/starrail/code'
  }
}
`
