### ISSUE TITLE
StarRailApi statusCode 502 

### ISSUE THREAD

**Issue by thangkhoei1030** [torikushiii/hoyolab-auto#62]
I'm using docker for this project and getting this error. I tried looking for open issues but it doesn't seem to be the same as my error. Hope to get any solution. Thanks a lot !!!
```
hoyolab-auto  | 
hoyolab-auto  | > start
hoyolab-auto  | > node index.js
hoyolab-auto  | 
hoyolab-auto  | 2024-09-14 20:37:54 <INFO:System> Log level set to info
hoyolab-auto  | 2024-09-14 20:37:54 <INFO:Client> Loading configuration data
hoyolab-auto  | 2024-09-14 20:37:54 <INFO:Client> Loaded 5 configuration entries
hoyolab-auto  | 2024-09-14 20:37:54 <WARN:Client> Skipping discord platform (inactive)
hoyolab-auto  | 2024-09-14 20:37:54 <WARN:Client> Skipping telegram platform (inactive)
hoyolab-auto  | 2024-09-14 20:37:54 <INFO:Cron> Initialized 11 cron jobs
hoyolab-auto  | 2024-09-14 20:37:54 <WARN:Client> Skipping honkai account (inactive)
hoyolab-auto  | 2024-09-14 20:37:54 <WARN:Client> Skipping termis account (inactive)
hoyolab-auto  | 2024-09-14 20:37:54 <WARN:Client> Skipping zenless account (inactive)
hoyolab-auto  | 2024-09-14 20:37:54 <INFO:GenshinImpact> Logged into (862173727) Huma (SEA)
hoyolab-auto  | 2024-09-14 20:37:54 <INFO:StarRail> Logged into (800961197) Miiya (SEA)
hoyolab-auto  | 2024-09-14 20:37:54 <INFO:Client> Initialize completed (705.451047ms)
hoyolab-auto  | 2024-09-14 20:40:00 <INFO:StarRail:StarRailAPI> { statusCode: 502 }
hoyolab-auto  | 2024-09-14 20:40:21 <INFO:GotRequest> {
hoyolab-auto  |   error: RequestError
hoyolab-auto  |       at Request._beforeError (file:///app/node_modules/got/dist/source/core/index.js:184:21)
hoyolab-auto  |       at Request.flush (file:///app/node_modules/got/dist/source/core/index.js:173:18)
hoyolab-auto  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)AggregateError [ETIMEDOUT]: 
hoyolab-auto  |       at internalConnectMultiple (node:net:1118:18)
hoyolab-auto  |       at afterConnectMultiple (node:net:1685:7) {
hoyolab-auto  |     input: undefined,
hoyolab-auto  |     code: 'ETIMEDOUT',
hoyolab-auto  |     timings: undefined,
hoyolab-auto  |     options: {
hoyolab-auto  |       request: undefined,
hoyolab-auto  |       agent: { http: undefined, https: undefined, http2: undefined },
hoyolab-auto  |       h2session: undefined,
hoyolab-auto  |       decompress: true,
hoyolab-auto  |       timeout: {
hoyolab-auto  |         connect: undefined,
hoyolab-auto  |         lookup: undefined,
hoyolab-auto  |         read: undefined,
hoyolab-auto  |         request: 30000,
hoyolab-auto  |         response: undefined,
hoyolab-auto  |         secureConnect: undefined,
hoyolab-auto  |         send: undefined,
hoyolab-auto  |         socket: undefined
hoyolab-auto  |       },
hoyolab-auto  |       prefixUrl: '',
hoyolab-auto  |       body: undefined,
hoyolab-auto  |       form: undefined,
hoyolab-auto  |       json: undefined,
hoyolab-auto  |       cookieJar: undefined,
hoyolab-auto  |       ignoreInvalidCookies: false,
hoyolab-auto  |       searchParams: undefined,
hoyolab-auto  |       dnsLookup: undefined,
hoyolab-auto  |       dnsCache: undefined,
hoyolab-auto  |       context: {},
hoyolab-auto  |       hooks: {
hoyolab-auto  |         init: [],
hoyolab-auto  |         beforeRequest: [],
hoyolab-auto  |         beforeError: [ [AsyncFunction (anonymous)] ],
hoyolab-auto  |         beforeRedirect: [],
hoyolab-auto  |         beforeRetry: [],
hoyolab-auto  |         afterResponse: []
hoyolab-auto  |       },
hoyolab-auto  |       followRedirect: true,
hoyolab-auto  |       maxRedirects: 10,
hoyolab-auto  |       cache: undefined,
hoyolab-auto  |       throwHttpErrors: false,
hoyolab-auto  |       username: '',
hoyolab-auto  |       password: '',
hoyolab-auto  |       http2: true,
hoyolab-auto  |       allowGetBody: false,
hoyolab-auto  |       headers: {
hoyolab-auto  |         'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36',
hoyolab-auto  |         'accept-encoding': 'gzip, deflate, br'
hoyolab-auto  |       },
hoyolab-auto  |       methodRewriting: false,
hoyolab-auto  |       dnsLookupIpVersion: undefined,
hoyolab-auto  |       parseJson: [Function: parse],
hoyolab-auto  |       stringifyJson: [Function: stringify],
hoyolab-auto  |       retry: {
hoyolab-auto  |         limit: 0,
hoyolab-auto  |         methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
hoyolab-auto  |         statusCodes: [
hoyolab-auto  |           408, 413, 429, 500,
hoyolab-auto  |           502, 503, 504, 521,
hoyolab-auto  |           522, 524
hoyolab-auto  |         ],
hoyolab-auto  |         errorCodes: [
hoyolab-auto  |           'ETIMEDOUT',
hoyolab-auto  |           'ECONNRESET',
hoyolab-auto  |           'EADDRINUSE',
hoyolab-auto  |           'ECONNREFUSED',
hoyolab-auto  |           'EPIPE',
hoyolab-auto  |           'ENOTFOUND',
hoyolab-auto  |           'ENETUNREACH',
hoyolab-auto  |           'EAI_AGAIN'
hoyolab-auto  |         ],
hoyolab-auto  |         maxRetryAfter: undefined,
hoyolab-auto  |         calculateDelay: [Function: calculateDelay],
hoyolab-auto  |         backoffLimit: Infinity,
hoyolab-auto  |         noise: 100
hoyolab-auto  |       },
hoyolab-auto  |       localAddress: undefined,
hoyolab-auto  |       method: 'GET',
hoyolab-auto  |       createConnection: undefined,
hoyolab-auto  |       cacheOptions: {
hoyolab-auto  |         shared: undefined,
hoyolab-auto  |         cacheHeuristic: undefined,
hoyolab-auto  |         immutableMinTimeToLive: undefined,
hoyolab-auto  |         ignoreCargoCult: undefined
hoyolab-auto  |       },
hoyolab-auto  |       https: {
hoyolab-auto  |         alpnProtocols: undefined,
hoyolab-auto  |         rejectUnauthorized: undefined,
hoyolab-auto  |         checkServerIdentity: undefined,
hoyolab-auto  |         certificateAuthority: undefined,
hoyolab-auto  |         key: undefined,
hoyolab-auto  |         certificate: undefined,
hoyolab-auto  |         passphrase: undefined,
hoyolab-auto  |         pfx: undefined,
hoyolab-auto  |         ciphers: undefined,
hoyolab-auto  |         honorCipherOrder: undefined,
hoyolab-auto  |         minVersion: undefined,
hoyolab-auto  |         maxVersion: undefined,
hoyolab-auto  |         signatureAlgorithms: undefined,
hoyolab-auto  |         tlsSessionLifetime: undefined,
hoyolab-auto  |         dhparam: undefined,
hoyolab-auto  |         ecdhCurve: undefined,
hoyolab-auto  |         certificateRevocationLists: undefined
hoyolab-auto  |       },
hoyolab-auto  |       encoding: undefined,
hoyolab-auto  |       resolveBodyOnly: false,
hoyolab-auto  |       isStream: false,
hoyolab-auto  |       responseType: 'text',
hoyolab-auto  |       url: URL {
hoyolab-auto  |         href: 'https://genshin-impact.fandom.com/wiki/Promotional_Code',
hoyolab-auto  |         origin: 'https://genshin-impact.fandom.com',
hoyolab-auto  |         protocol: 'https:',
hoyolab-auto  |         username: '',
hoyolab-auto  |         password: '',
hoyolab-auto  |         host: 'genshin-impact.fandom.com',
hoyolab-auto  |         hostname: 'genshin-impact.fandom.com',
hoyolab-auto  |         port: '',
hoyolab-auto  |         pathname: '/wiki/Promotional_Code',
hoyolab-auto  |         search: '',
hoyolab-auto  |         searchParams: URLSearchParams {},
hoyolab-auto  |         hash: ''
hoyolab-auto  |       },
hoyolab-auto  |       pagination: {
hoyolab-auto  |         transform: [Function: transform],
hoyolab-auto  |         paginate: [Function: paginate],
hoyolab-auto  |         filter: [Function: filter],
hoyolab-auto  |         shouldContinue: [Function: shouldContinue],
hoyolab-auto  |         countLimit: Infinity,
hoyolab-auto  |         backoff: 0,
hoyolab-auto  |         requestLimit: 10000,
hoyolab-auto  |         stackAllItems: false
hoyolab-auto  |       },
hoyolab-auto  |       setHost: true,
hoyolab-auto  |       maxHeaderSize: undefined,
hoyolab-auto  |       signal: undefined,
hoyolab-auto  |       enableUnixSockets: false
hoyolab-auto  |     },
hoyolab-auto  |     [cause]: AggregateError [ETIMEDOUT]: 
hoyolab-auto  |         at internalConnectMultiple (node:net:1118:18)
hoyolab-auto  |         at afterConnectMultiple (node:net:1685:7) {
hoyolab-auto  |       code: 'ETIMEDOUT',
hoyolab-auto  |       [errors]: [Array]
hoyolab-auto  |     }
hoyolab-auto  |   },
hoyolab-auto  |   context: {
hoyolab-auto  |     code: 'ETIMEDOUT',
hoyolab-auto  |     responseType: 'text',
hoyolab-auto  |     timeout: {
hoyolab-auto  |       connect: undefined,
hoyolab-auto  |       lookup: undefined,
hoyolab-auto  |       read: undefined,
hoyolab-auto  |       request: 30000,
hoyolab-auto  |       response: undefined,
hoyolab-auto  |       secureConnect: undefined,
hoyolab-auto  |       send: undefined,
hoyolab-auto  |       socket: undefined
hoyolab-auto  |     },
hoyolab-auto  |     url: 'https://genshin-impact.fandom.com/wiki/Promotional_Code'
hoyolab-auto  |   }
hoyolab-auto  | }
hoyolab-auto  | 2024-09-14 20:45:01 <INFO:StarRail:StarRailAPI> { statusCode: 502 }
```

**Comment by torikushiii** [comment]
it  was because the API is down at that time, but this error can be safely ignored and it will resolve itself
